### ISSUE TITLE
Left align text in dropdown boxes

### ISSUE THREAD

**Issue by oakif** [jac3km4/comfyweb#2]
I think it would be a good idea to left-align text since that's generally how text is aligned in most UIs. Otherwise, it can be a little confusing! 

![image](https://user-images.githubusercontent.com/48932412/224411389-096031df-e88b-40c7-ace6-168fc241c328.png)

**Comment by jac3km4** [comment]
![image](https://user-images.githubusercontent.com/11986158/224424484-20f4a907-e67c-4973-88fa-c0e770ec1e47.png)

This is what it looks like left-aligned, I have a slight preference for right-aligned because the input boxes extend to the right and they're aligned from the right side, but I'm open to suggestions.

**Comment by Runbiorn** [comment]
I had this thought too.

I organize checkpoints/loras/etc. into subfolders, and it's very difficult to parse with right-alignment because the folder structure becomes a visual mess. If it were left-aligned, the folder structure would be correctly aligned and it would be easier to tell at a glance which subfolder each item is in.

The ideal would maybe be left-aligned file selection drop-down lists and right aligned everything else, if that's possible.

**Comment by oakif** [comment]
For the record, I completely agree with that, but I've still never seen right-aligned text in a dropdown before. I presume it's because it makes the UI look less visually appealing. 

Typically the way I've seen this issue overcome is by putting ellipses before the name. For example, the dropdown would show something like 

```
.../folder6A/folder7A/anything.ckpt
.../folder8B/folder9B/deliberate.ckpt
```

This is how the mobile version of Google search shows completions for long search items on a smaller screen. I also recall this type of behavior in a Lightroom plugin I use.

**Comment by jac3km4** [comment]
I've changed how the alignment works and added left-ellipsis on master, let me know what you think @oakif @Enantiomorph

**Comment by jac3km4** [comment]
closing because the UI has been re-worked
